const translations={ar:{title:"سيرفر علَم كرافت ☘️",copyBtn:"نسخ الـ IP:PORT ",javaVersion:"☕️ جافا:",bedrockVersion:"🛏️ بيدروك:",addBedrock:"إضافة السيرفر إلى ماينكرافت البيدروك",rulesTitle:"📜 القوانين",linksTitle:"🔗 روابط السيرفر",adminsTitle:"👑 المشرفين",adminsNames:"علَم جيمر ☘️، الثعلب المفقود 🦊، ملك الجليد 👑❄️",copyright:"© 2026 AlamCraft Server - جميع الحقوق محفوظة",toastMsg:"✔ تم نسخ IP:PORT السيرفر بنجاح",serverOnline:"السيرفر متصل",serverOffline:"السيرفر مغلق",playersOnline:"اللاعبين المتصلين:",loading:"جاري التحقق...",modsTitle:"المودات/الإضافات",downloadCenterBtn:"مركز التحميل"},en:{title:"AlamCraft Server ☘️",copyBtn:"Copy IP:PORT",javaVersion:"☕️ Java:",bedrockVersion:"🛏️ Bedrock:",addBedrock:"Add Server to Minecraft Bedrock",rulesTitle:"📜 Server Rules",linksTitle:"🔗 Server Links",adminsTitle:"👑 Staff",adminsNames:"AlamGamer ☘️,LostFox 🦊,KingSnow 👑❄️",copyright:"© 2026 AlamCraft Server-All Rights Reserved",toastMsg:"✔ Server IP:PORT Copied!",serverOnline:"Server Online",serverOffline:"Server Offline",playersOnline:"Players Online:",loading:"Checking status...",modsTitle:"Mods/Plugins",downloadCenterBtn:"Download Center"}};let currentLang=localStorage.getItem("lang")||"ar";const $=s=>document.querySelector(s);const statusIndicator=$("#status-indicator"),statusText=$("#status-text"),playerNum=$("#player-num"),maxPlayers=$("#max-players"),pingValue=$("#ping-value"),modsListContainer=$("#mods-list-container"),toast=$("#toast"),sideMenu=$("#sideMenu"),menuOverlay=$("#menuOverlay"),modeBtn=$("#modeBtn"),socialLinks=$(".social-links");
function renderAlamChatBtn(){if(!socialLinks)return;const old=document.querySelector(".alamchat-btn");if(old)old.remove();const a=document.createElement("a");a.href="https://acrft.github.io/achat";a.className="social-item alamchat-btn";a.target="_blank";const img=document.createElement("img");img.src="images/achat.png";img.className="link-icon";const span=document.createElement("span");span.textContent=currentLang==="ar"?"منصة علم شات":"Alam Chat Platform";a.append(img,span);socialLinks.prepend(a);}
function toggleMenu(){sideMenu.classList.toggle("active");menuOverlay.classList.toggle("active");}
function setOfflineUI(){statusText.innerText=translations[currentLang].serverOffline+" ❌";playerNum.innerText="0";maxPlayers.innerText="0";pingValue.innerText="--";}
async function updateServerStatus(){try{const res=await fetch(`https://api.mcsrvstat.us/2/alameldin.aternos.me:28303?t=${Date.now()}`);const data=await res.json();if(!data.online){setOfflineUI();return;}statusText.innerText=translations[currentLang].serverOnline+" ✅";playerNum.innerText=data.players?.online||0;maxPlayers.innerText=data.players?.max||0;}catch{setOfflineUI();}}
function updateContent(){document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(translations[currentLang][k])el.innerText=translations[currentLang][k];});document.documentElement.lang=currentLang;document.documentElement.dir=currentLang==="ar"?"rtl":"ltr";renderAlamChatBtn();updateServerStatus();}
function toggleLanguage(){currentLang=currentLang==="ar"?"en":"ar";localStorage.setItem("lang",currentLang);updateContent();}
function copyIP(){navigator.clipboard.writeText("Alameldin.aternos.me:28303");toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),3000);}
window.onload=()=>{updateContent();setInterval(updateServerStatus,30000);};
